version: '3'

services:

  htpasswd:
    image: sofocused/htpasswd:1.0
    command: >
      sh -c "python generator.py -u admin -p admin --path /htpasswd && tail -f /dev/null"
    volumes:
      - htpasswd:/app/htpasswd/

  prometheus-service:
    image: prom/prometheus:v2.53.1
    restart: unless-stopped
    container_name: prometheus
    command: 
    - --web.external-url=http://frontend:80/prometheus/
    - --web.route-prefix=/
    - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    volumes:
      - prometheus-storage:/prometheus
      - ./monitoring/prometheus:/etc/prometheus

  grafana-service:
    image: grafana/grafana:9.5.2
    restart: unless-stopped
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost:80
      - GF_SERVER_ROOT_URL=http://frontend-service:80/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    expose:
      - 3000
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana

  frontend:
    image: sofocused/job-post-frontend:1.1.3
    restart: unless-stopped
    depends_on:
      - htpasswd
      - backend-service
      - prometheus-service
      - grafana-service
    ports:
      - "80:80"
    volumes:
      - htpasswd:/etc/nginx/htpasswd

  backend-service:
    image: sofocused/job-post-api:1.1.0
    restart: unless-stopped
    depends_on:
      job-post-database:
        condition: service_healthy
    environment:
      - SPRING_FLYWAY_ENABLED=false
      - SPRING_FLYWAY_URL=jdbc:postgresql://job-post-database/testdb
      - SPRING_FLYWAY_PASSWORD=admin
      - SPRING_FLYWAY_USER=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://job-post-database/testdb
      - SPRING_JPA_SHOWSQL=false
      - CORS_ALLOWEDORIGINS=http://localhost:3000

  job-post-database:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ~\postgres_container_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=testdb
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER}  -d $${POSTGRES_DB}"
      interval: 10s
      timeout: 30s
      retries: 10

volumes:
  grafana-storage: {}
  prometheus-storage: {}
  htpasswd: {}