version: '3'

services:

  frontend:
    image: sofocused/job-post-frontend:1.0.7
    restart: unless-stopped
    ports:
      - "80:80"

  backend-service:
    image: sofocused/job-post-api:1.0.7
    restart: unless-stopped
    depends_on:
      - job-post-database
    environment:
      - SPRING_FLYWAY_URL=jdbc:postgresql://job-post-database/testdb
      - SPRING_FLYWAY_PASSWORD=admin
      - SPRING_FLYWAY_USER=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://job-post-database/testdb
      - SPRING_JPA_SHOWSQL=false
      - CORS_ALLOWEDORIGINS=http://localhost:3000

  job-post-database:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - C:\postgres_container_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=testdb
