scrape_configs:
  - job_name: 'JobPostApp'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['backend-service:8080']
        labels:
          application: 'Job Post Application'